<table border='1' width='100%'  class="table table-striped"><thead><tr class='list-group-item list-group-item-action'><td>ID</td><td> BasesCode</td><td> TitleCode</td><td> DocType</td><td> DocLang</td><td> DocTitle</td><td> DocTitleSort</td><td> DocMode</td><td> RemFlag</td><td> DocTitleView</td><td> InterlineSpace</td><td> XID</td><td> RefCode</td><td> CategoryRef</td></tr></thead>

    <tbody><tr class='list-group-item list-group-item-action'><td>396</td><td> 1</td><td> 434</td><td> 1</td><td> 1</td><td> جهانگردی مارکوپولو ;بمناسبتهفتصدمین سال تولد جهانگرد ایتالیائی </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> جهانگردی مارکوپولو ;بمناسبتهفتصدمین سال تولد جهانگرد ایتالیائی </td></tr>
    <tr class='list-group-item list-group-item-action'><td>4057</td><td> 1</td><td> 3318</td><td> 1</td><td> 1</td><td> شناخت استان هرمزگان </td><td> X</td><td> 0</td><td> 0</td><td> مجموعه ای از تاریخ، جغرافیا، آثار باستانی ، جاذبه های جهانگردی ...</td><td> </td><td> 0</td><td> ##NULL##</td><td> مجموعه ای از تاریخ، جغرافیا، آثار باستانی ، جاذبه های جهانگردی ...</td></tr>
    <tr class='list-group-item list-group-item-action'><td>2378</td><td> 1</td><td> 1644</td><td> 1</td><td> 1</td><td> جغرافیای تاریخی خراسان از نظر جهانگردان </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> جغرافیای تاریخی خراسان از نظر جهانگردان </td></tr>
    <tr class='list-group-item list-group-item-action'><td>3678</td><td> 1</td><td> 2883</td><td> 1</td><td> 1</td><td> جغرافیای تاریخی گیلان ، مازندران ، آذربایجان از نظر جهانگردان </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> جغرافیای تاریخی گیلان ، مازندران ، آذربایجان از نظر جهانگردان </td></tr>
    <tr class='list-group-item list-group-item-action'><td>3876</td><td> 1</td><td> 3133</td><td> 1</td><td> 1</td><td> جهانگردی </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> جهانگردی </td></tr>
    <tr class='list-group-item list-group-item-action'><td>4152</td><td> 1</td><td> 3421</td><td> 1</td><td> 1</td><td> شناخت استان مرکزی : مجموعه ای از تاریخ، جغرافیا، آثار باستانی ، جاذبه های  جهانگردی ، شهرستانها، آداب رسومو اقتصاد منطقه </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> شناخت استان مرکزی : مجموعه ای از تاریخ، جغرافیا، آثار باستانی ، جاذبه های  جهانگردی ، شهرستانها، آداب رسومو اقتصاد منطقه </td></tr>
    <tr class='list-group-item list-group-item-action'><td>6979</td><td> 1</td><td> 6694</td><td> 1</td><td> 1</td><td> مکالمات روزمره انگلیسی ، فرانسه ، آلمانی ، ایتالیائی ، اسپانیولی به فارسی : راهنمای جهانگردان </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> مکالمات روزمره انگلیسی ، فرانسه ، آلمانی ، ایتالیائی ، اسپانیولی به فارسی : راهنمای جهانگردان </td></tr>
    <tr class='list-group-item list-group-item-action'><td>7836</td><td> 1</td><td> 7751</td><td> 1</td><td> 1</td><td> دختر یونان : ستاره ی سینما و تئاتر مبارز سیاسی علیه رژیم سرهنگان و وزیر سابق فرهنگ و جهانگردی یونان </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> دختر یونان : ستاره ی سینما و تئاتر مبارز سیاسی علیه رژیم سرهنگان و وزیر سابق فرهنگ و جهانگردی یونان </td></tr>
    <tr class='list-group-item list-group-item-action'><td>15434</td><td> 1</td><td> 15202</td><td> 1</td><td> 1</td><td> راهنمای جهانگردی دور دنیا</td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> راهنمای جهانگردی دور دنیا</td></tr>
    <tr class='list-group-item list-group-item-action'><td>15933</td><td> 1</td><td> 15837</td><td> 1</td><td> 1</td><td> ده سفرنامه ، یا، سیری در سفرنامه های جهانگردان خارجی راجع به ایران </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> ده سفرنامه ، یا، سیری در سفرنامه های جهانگردان خارجی راجع به ایران </td></tr>
    <tr class='list-group-item list-group-item-action'><td>22271</td><td> 1</td><td> 22430</td><td> 1</td><td> 1</td><td> اصول و مبانی جهانگردی </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> اصول و مبانی جهانگردی </td></tr>
    <tr class='list-group-item list-group-item-action'><td>31360</td><td> 1</td><td> 31402</td><td> 1</td><td> 1</td><td> شناخت جهانگردی </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> شناخت جهانگردی </td></tr>
    <tr class='list-group-item list-group-item-action'><td>34082</td><td> 1</td><td> 33988</td><td> 1</td><td> 1</td><td> برنامه ریزی ملی و منطقه ای جهانگردی </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> برنامه ریزی ملی و منطقه ای جهانگردی </td></tr>
    <tr class='list-group-item list-group-item-action'><td>37096</td><td> 1</td><td> 37147</td><td> 1</td><td> 1</td><td> جهانگردان مسلمان در دوره میانی </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> جهانگردان مسلمان در دوره میانی </td></tr>
    <tr class='list-group-item list-group-item-action'><td>37097</td><td> 1</td><td> 37148</td><td> 1</td><td> 1</td><td> جهانگردان مسلمان در قرون وسطی </td><td> X</td><td> 0</td><td> 0</td><td> </td><td> </td><td> 0</td><td> ##NULL##</td><td> جهانگردان مسلمان در قرون وسطی </td></tr>
    </tbody></table>